print("Billing Module")
print(10+5)
print(12*4)
print(25-8)
print(30/7)
print(30%3)

print("Information Display Module")
print("welcome to the national art museum")
print("Digital exhibits were introduced in 2015")
